web:
  image: youkke/ykcourse
  ports:
    - "6014:6014"
  environment:
    - VIRTUAL_HOST=localhost
  links:
    - redis:redis
    - mariadb:mariadb
redis:
  image: redis:3
mariadb:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=ykcourse
  volumes:
    - ./src/main/docker:/docker-entrypoint-initdb.d